[marketplaces.revit-skills]
source_type = "git"
source = "https://github.com/Nice3point/revit-skills.git"

[marketplaces.dotnet-agent-skills]
source_type = "git"
source = "https://github.com/dotnet/skills.git"

[plugins."revit-api@revit-skills"]
enabled = true

[plugins."revit-ui@revit-skills"]
enabled = true

[plugins."revit-solution@revit-skills"]
enabled = true

[plugins."revit-testing@revit-skills"]
enabled = true

[plugins."dotnet@revit-skills"]
enabled = true

[plugins."dotnet-advanced@revit-skills"]
enabled = true

[plugins."dotnet-test@dotnet-agent-skills"]
enabled = true
