using RevitLookup.Abstractions.Services.Settings;

namespace RevitLookup.UI.Framework.Converters.ValueConverters;

public sealed class SoftwareUpdateStateCollapsedVisibilityConverter : EnumCollapsedVisibilityConverter<SoftwareUpdateState>;